# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: SafeNetworkingSkillet
# label used for menu selection
label: safe_networking_skillet
description: Configures Safe Networking on NGFW

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - SafeNetworking

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints examples include text, ip_address, or dropdown
variables:
  - name: SFN_Server
    description: SFN Server IP
    default: 10.10.10.10
    type_hint: ip_address
  - name: Security_Rule
    description: Rule to apply LF and Security profiles to
    default: SFN-test
    type_hint: text
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
snippets:
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order
  - name: shared_log_settings
    xpath: /config/shared/log-settings
    element: |- 
      <syslog>
        <entry name="syslog-SFN-5514">
          <server>
            <entry name="SFN-server">
              <transport>TCP</transport>
              <port>5514</port>
              <format>BSD</format>
              <server>{{ SFN_Server }}</server>
              <facility>LOG_USER</facility>
            </entry>
          </server>
        </entry>
      </syslog>
  - name: security_profiles
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/profiles
    element: |-
      <url-filtering>
        <entry name="SFN-Alert">
          <credential-enforcement>
            <mode>
              <disabled/>
            </mode>
            <log-severity>medium</log-severity>
          </credential-enforcement>
          <safe-search-enforcement>no</safe-search-enforcement>
          <alert>
            <member>abortion</member>
            <member>abused-drugs</member>
            <member>adult</member>
            <member>alcohol-and-tobacco</member>
            <member>auctions</member>
            <member>business-and-economy</member>
            <member>command-and-control</member>
            <member>computer-and-internet-info</member>
            <member>content-delivery-networks</member>
            <member>copyright-infringement</member>
            <member>cryptocurrency</member>
            <member>dating</member>
            <member>dynamic-dns</member>
            <member>educational-institutions</member>
            <member>entertainment-and-arts</member>
            <member>extremism</member>
            <member>financial-services</member>
            <member>gambling</member>
            <member>games</member>
            <member>government</member>
            <member>grayware</member>
            <member>hacking</member>
            <member>health-and-medicine</member>
            <member>high-risk</member>
            <member>home-and-garden</member>
            <member>hunting-and-fishing</member>
            <member>insufficient-content</member>
            <member>internet-communications-and-telephony</member>
            <member>internet-portals</member>
            <member>job-search</member>
            <member>legal</member>
            <member>low-risk</member>
            <member>malware</member>
            <member>medium-risk</member>
            <member>military</member>
            <member>motor-vehicles</member>
            <member>music</member>
            <member>newly-registered-domain</member>
            <member>news</member>
            <member>not-resolved</member>
            <member>nudity</member>
            <member>online-storage-and-backup</member>
            <member>parked</member>
            <member>peer-to-peer</member>
            <member>personal-sites-and-blogs</member>
            <member>philosophy-and-political-advocacy</member>
            <member>phishing</member>
            <member>private-ip-addresses</member>
            <member>proxy-avoidance-and-anonymizers</member>
            <member>questionable</member>
            <member>real-estate</member>
            <member>recreation-and-hobbies</member>
            <member>reference-and-research</member>
            <member>religion</member>
            <member>search-engines</member>
            <member>sex-education</member>
            <member>shareware-and-freeware</member>
            <member>shopping</member>
            <member>social-networking</member>
            <member>society</member>
            <member>sports</member>
            <member>stock-advice-and-tools</member>
            <member>streaming-media</member>
            <member>swimsuits-and-intimate-apparel</member>
            <member>training-and-tools</member>
            <member>translation</member>
            <member>travel</member>
            <member>unknown</member>
            <member>weapons</member>
            <member>web-advertisements</member>
            <member>web-based-email</member>
            <member>web-hosting</member>
          </alert>
          <mlav-engine-urlbased-enabled>
            <entry name="Phishing Detection">
              <mlav-policy-action>allow</mlav-policy-action>
            </entry>
            <entry name="Javascript Exploit Detection">
              <mlav-policy-action>allow</mlav-policy-action>
            </entry>
          </mlav-engine-urlbased-enabled>
        </entry>
      </url-filtering>
      <spyware>
        <entry name="SFN-Alert">
          <botnet-domains>
            <lists>
              <entry name="default-paloalto-dns">
                <action>
                  <sinkhole/>
                </action>
                <packet-capture>disable</packet-capture>
              </entry>
            </lists>
            <dns-security-categories>
              <entry name="pan-dns-sec-benign">
                <log-level>default</log-level>
                <action>default</action>
                <packet-capture>disable</packet-capture>
              </entry>
              <entry name="pan-dns-sec-cc">
                <log-level>default</log-level>
                <action>default</action>
                <packet-capture>disable</packet-capture>
              </entry>
              <entry name="pan-dns-sec-ddns">
                <log-level>default</log-level>
                <action>default</action>
                <packet-capture>disable</packet-capture>
              </entry>
              <entry name="pan-dns-sec-malware">
                <log-level>default</log-level>
                <action>default</action>
                <packet-capture>disable</packet-capture>
              </entry>
              <entry name="pan-dns-sec-phishing">
                <log-level>default</log-level>
                <action>default</action>
                <packet-capture>disable</packet-capture>
              </entry>
              <entry name="pan-dns-sec-recent">
                <log-level>default</log-level>
                <action>default</action>
                <packet-capture>disable</packet-capture>
              </entry>
            </dns-security-categories>
            <sinkhole>
              <ipv4-address>pan-sinkhole-default-ip</ipv4-address>
              <ipv6-address>::1</ipv6-address>
            </sinkhole>
          </botnet-domains>
          <rules>
            <entry name="SFN-Anti-Spyware">
              <action>
                <alert/>
              </action>
              <severity>
                <member>any</member>
              </severity>
              <threat-name>any</threat-name>
              <category>any</category>
              <packet-capture>disable</packet-capture>
            </entry>
          </rules>
        </entry>
      </spyware>
      <vulnerability>
        <entry name="SFN-Alert">
          <rules>
            <entry name="SFN-Vulnerability-Alert">
              <action>
                <alert/>
              </action>
              <vendor-id>
                <member>any</member>
              </vendor-id>
              <severity>
                <member>any</member>
              </severity>
              <cve>
                <member>any</member>
              </cve>
              <threat-name>any</threat-name>
              <host>any</host>
              <category>any</category>
              <packet-capture>disable</packet-capture>
            </entry>
          </rules>
        </entry>
      </vulnerability>
    
  - name: log_forwarding_profile
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/log-settings
    element: |-
      <profiles>
        <entry name="SFN-Log-Forwarding">
          <match-list>
            <entry name="Syslog-Traffic-SFN">
              <send-syslog>
                <member>syslog-SFN-5514</member>
              </send-syslog>
              <log-type>traffic</log-type>
              <filter>All Logs</filter>
              <send-to-panorama>no</send-to-panorama>
              <quarantine>no</quarantine>
            </entry>
            <entry name="Syslog-Threat-SFN">
              <send-syslog>
                <member>syslog-SFN-5514</member>
              </send-syslog>
              <log-type>threat</log-type>
              <filter>All Logs</filter>
              <send-to-panorama>no</send-to-panorama>
              <quarantine>no</quarantine>
            </entry>
          </match-list>
        </entry>
      </profiles>
  - name: security_rulebase
    xpath: /config/devices/entry[@name='localhost.localdomain']/vsys/entry[@name='vsys1']/rulebase
    element: |-
      <security>
        <rules>
          <entry name="{{ Security_Rule }}">
            <profile-setting>
              <profiles>
                <url-filtering>
                  <member>SFN-Alert</member>
                </url-filtering>
                <spyware>
                  <member>SFN-Alert</member>
                </spyware>
                <vulnerability>
                  <member>SFN-Alert</member>
                </vulnerability>
              </profiles>
            </profile-setting>
            <to>
              <member>any</member>
            </to>
            <from>
              <member>any</member>
            </from>
            <source>
              <member>any</member>
            </source>
            <destination>
              <member>any</member>
            </destination>
            <source-user>
              <member>any</member>
            </source-user>
            <category>
              <member>any</member>
            </category>
            <application>
              <member>any</member>
            </application>
            <service>
              <member>application-default</member>
            </service>
            <source-hip>
              <member>any</member>
            </source-hip>
            <destination-hip>
              <member>any</member>
            </destination-hip>
            <action>allow</action>
            <log-setting>SFN-Log-Forwarding</log-setting>
          </entry>
        </rules>
      </security>

# ---------------------------------------------------------------------
# end of snippets section